project:
  name: "OCP Certificate Api"
  author: "Vadim Prosviryakov"
  version: "0.0.1"

grpc:
  address: ":8082"

rest:
  address: ":8081"

database:
  host: "postgres"
  port: "5432"
  user: "postgres"
  password: "postgres"
  database: "postgres"
  sslmode: "disable"
  driver: "postgres"

batchSize: 10

prometheus:
  uri: "/metrics"
  port: ":9100"

jaeger:
  host: "jaeger"
  port: ":6831"

kafka:
  topic: "certificate"
  brokers:
    - "kafka:9092"