version: "3.9"

services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - ocpca
    volumes:
      - pgdata:/var/lib/postgresql/data

  ocp-certificate-api:
    build: .
    restart: unless-stopped
    networks:
      - ocpca
    depends_on:
      - postgres
      - kafka
    links:
      - postgres
    ports:
      - 8081:8081 # rest
      - 8082:8082 # grpc
      - 9100:9100 # prometheus

  zookeeper:
    image: confluentinc/cp-zookeeper
    restart: unless-stopped
    ports:
      - 2181:2181
    environment:
      zk_id: "1"
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
    networks:
      - ocpca

  kafka:
    image: confluentinc/cp-kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - 9094:9094
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:32181"
      KAFKA_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://kafka:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - ocpca

  kafka-ui:
    image: obsidiandynamics/kafdrop
    restart: unless-stopped
    depends_on:
      - kafka
    ports:
      - 9000:9000
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    networks:
      - ocpca

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - 8080:8080
    restart: always
    volumes:
      - ./swagger:/docs
    environment:
      SWAGGER_JSON: /docs/api.swagger.json
    depends_on:
      - ocp-certificate-api
    networks:
      - ocpca

  jaeger:
    image: jaegertracing/all-in-one
    restart: unless-stopped
    ports:
      - 6831:6831/udp
      - 16686:16686
    networks:
      - ocpca

  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - ocpca

volumes:
  pgdata:

networks:
  ocpca:
    driver: bridge